---
title: "ggridge_Pilot items"
author: "Tong"
date: "`r Sys.Date()`"
output: html_document
---


```{r load packages}
library(ggridges)
library(tidyverse)
library(data.table)
library(epiR)
library(patchwork)
library(ggplot2)
```

I exclude 10 participants. Two participants stated that they were not serious when answering the survey. Eight participants suggested that they don't speak German in the demographic question
```{r load data and data exclusion}
df <- read.csv("clean_pilot.csv")

df <- df %>% filter(df$quality != "notserious")
df <- df %>% filter(df$language != "not_german")
```

```{r define indifferent_events vector (diff_event)}
diff_event <- c("In einem zufällig ausgewählten deutschen Haushalt gibt es einen Trockner." ,
   "In einem zufällig ausgewählten deutschen Haushalt gibt es KEINEN Trockner.",
"Eine zufällig ausgewählte Person in Deutschland hat NICHT mehr als zwei Geschwister.",   
"Eine zufällig ausgewählte Person in Deutschland hat mehr als zwei Geschwister.", 
"Eine zufällig ausgewählte Person in Deutschland trainiert täglich.",    
"Eine zufällig ausgewählte Person in Deutschland trainiert NICHT täglich.",
"Ein(e) zufällig ausgewählte(r) Student(in) in Deutschland hat KEINE Erfahrung mit dem Programmieren am Computer.",       
"Ein(e) zufällig ausgewählte(r) Student(in) in Deutschland hat ein bisschen Erfahrung mit dem Programmieren am Computer.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Facebook NICHT wöchentlich.", 
"Eine zufällig ausgewählte Person in Deutschland nutzt wöchentlich Facebook.",
 "Eine zufällig ausgewählte Person in Deutschland hat innerhalb der letzten Woche KEIN Buch zu Ende gelesen.",
"Eine zufällig ausgewählte Person in Deutschland hat innerhalb der letzten Woche ein Buch zu Ende gelesen.",
"An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer für ganz Deutschland NICHT über 4 Stunden liegen.",
"An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer für ganz Deutschland über 4 Stunden liegen.",
"Eine zufällig ausgewählte deutsche Person besucht an Weihnachten NICHT die Kirche.",     
"Eine zufällig ausgewählte deutsche Person besucht an Weihnachten die Kirche.",
"Eine zufällig ausgewählte Person in Deutschland wohnt in Süddeutschland.",
"Eine zufällig ausgewählte Person in Deutschland wohnt NICHT in Süddeutschland.",
"An einem zufällig ausgewählten Tag im Jahr wird die Temperatur in Deutschland über 15 °C liegen.",
"An einem zufällig ausgewählten Tag im Jahr wird die Temperatur in Deutschland NICHT über 15 °C liegen.",
"Eine zufällig ausgewählte Person in Deutschland ist Fan eines Fußballvereins.",
"Eine zufällig ausgewählte Person in Deutschland ist NICHT Fan eines Fußballvereins.",
"Eine zufällig ausgewählte Person in Deutschland ist noch NIE im Mittelmeer geschwommen.",
"Eine zufällig ausgewählte Person in Deutschland ist schon einmal im Mittelmeer geschwommen.",
"Ein zufällig ausgewähltes deutsches Schulkind lernt NICHT in der Schule ein Instrument zu spielen.",
"Ein zufällig ausgewähltes deutsches Schulkind lernt in der Schule ein Instrument zu spielen.",
"Eine zufällig ausgewählte Person in Deutschland wird irgendwann an Krebs sterben.",
"Eine zufällig ausgewählte Person in Deutschland wird NICHT irgendwann an Krebs sterben.", 
"Ein zufällig ausgewähltes Auto auf der Straße in Deutschland wurde NICHT in Deutschland hergestellt.",
"Ein zufällig ausgewähltes Auto auf der Straße in Deutschland wurde in Deutschland hergestellt.",
"In einem zufällig ausgewählten Jahr werden in Deutschland im April NICHT mehr Blumen blühen als im März.",
"In einem zufällig ausgewählten Jahr werden in Deutschland im April mehr Blumen blühen als im März.",
"Ein zufällig ausgewähltes Ehepaar in Deutschland hat mehr als zwei Kinder.",
"Ein zufällig ausgewähltes Ehepaar in Deutschland hat NICHT mehr als zwei Kinder.",
"Eine zufällig ausgewählte Person in Deutschland isst täglich Früchte.",
"Eine zufällig ausgewählte Person in Deutschland isst NICHT täglich Früchte.",
"Eine zufällig ausgewählte Person in Deutschland, die über 20 Jahre alt ist, hat einen Führerschein.",
"Eine zufällig ausgewählte Person in Deutschland, die über 20 Jahre alt ist, hat KEINEN Führerschein.",
"Eine zufällig ausgewählte Person in Deutschland ist NICHT verheiratet.",
"Eine zufällig ausgewählte Person in Deutschland ist verheiratet.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Twitter wöchentlich.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Twitter NICHT wöchentlich.",
"Eine zufällig ausgewählte Person in Deutschland schaut täglich YouTube-Videos.",
"Eine zufällig ausgewählte Person in Deutschland schaut NICHT täglich YouTube-Videos.",
"Ein zufällig ausgewählter Haushalt in Deutschland besitzt ein oder mehrere Haustiere.",
"Ein zufällig ausgewählter Haushalt in Deutschland besitzt KEINE Haustiere.",
"An einem zufällig ausgewählten Tag im Januar wird die Durchschnittstemperatur in Deutschland NICHT über 0°C liegen.",
"An einem zufällig ausgewählten Tag im Januar wird die Durchschnittstemperatur in Deutschland über 0°C liegen.",
"In einem zufällig ausgewählten Jahr wird die Blumenblüte im Rheintal vor März beginnen.",
"In einem zufällig ausgewählten Jahr wird die Blumenblüte im Rheintal NICHT vor März beginnen.", 
"An einem zufällig ausgewählten Tag im Oktober wird die Durchschnittstemperatur in Deutschland über 10 °C liegen.",
"An einem zufällig ausgewählten Tag im Oktober wird die Durchschnittstemperatur in Deutschland NICHT über 10 °C liegen.",
"Eine zufällig ausgewählte Person in Deutschland hat KEINEN Führerschein.",
"Eine zufällig ausgewählte Person in Deutschland hat einen Führerschein.",
"Die Anzahl der Katzen ist größer als die Anzahl der Hunde in einer zufällig ausgewählten deutschen Stadt.",
"Die Anzahl der Katzen ist NICHT größer als die Anzahl der Hunde in einer zufällig ausgewählten deutschen Stadt.",
"Eine zufällig ausgewählte Person in Deutschland war schon einmal in Japan.",
"Eine zufällig ausgewählte Person in Deutschland war noch NICHT in Japan.", 
"Eine zufällig ausgewählte Person in Deutschland isst täglich NICHT mehr als drei Gemüsesorten.", 
"Eine zufällig ausgewählte Person in Deutschland isst täglich mehr als drei Gemüsesorten.",
"Eine zufällig ausgewählte Person in Deutschland über 30 Jahre ist NICHT verheiratet.",
"Eine zufällig ausgewählte Person in Deutschland über 30 Jahre ist verheiratet.",
"In einem zufällig ausgewählten Jahr wird die niedrigste Temperatur in Deutschland unter -15°C liegen.",                                     
"In einem zufällig ausgewählten Jahr wird die niedrigste Temperatur in Deutschland NICHT unter -15°C liegen.",
"Eine zufällig ausgewählte Person in Deutschland nutzt monatlich Twitter.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Twitter NICHT monatlich.",
"Ein zufällig ausgewählter Pendler fährt NICHT mit dem Auto zur Arbeit.",
"Ein zufällig ausgewählter Pendler fährt mit dem Auto zur Arbeit.",
"Eine zufällig ausgewählte Person in Deutschland hat ein Twitter-Konto.",
"Eine zufällig ausgewählte Person in Deutschland hat KEIN Twitter-Konto.",
"In einem zufällig ausgewählten Jahr wird den ganzen Mai über Schnee auf dem Gipfel der Zugspitze in Deutschland sein.",
"In einem zufällig ausgewählten Jahr wird den ganzen Mai über KEIN Schnee auf dem Gipfel der Zugspitze in Deutschland sein.",
"Eine zufällig ausgewählte deutsche Person kann sich NICHT fließend auf Englisch unterhalten.",
"Eine zufällig ausgewählte deutsche Person kann sich fließend auf Englisch unterhalten.",
"Eine zufällig ausgewählte Person in Deutschland besucht an Weihnachten NICHT die Kirche.",
"Eine zufällig ausgewählte Person in Deutschland besucht an Weihnachten die Kirche.",
"An einem zufällig ausgewählten Tag in Hamburg wird es NICHT länger als 2 Stunden am Stück regnen.","An einem zufällig ausgewählten Tag in Hamburg wird es länger als 2 Stunden am Stück regnen.","Ein zufällig ausgewähltes Ehepaar in Deutschland hat zwei oder mehr Kinder.","Ein zufällig ausgewähltes Ehepaar in Deutschland hat NICHT zwei oder mehr Kinder.",
"In einem zufällig ausgewählten Jahr werden die Weinreben im Rheintal NICHT vor Mai blühen.",
"In einem zufällig ausgewählten Jahr werden die Weinreben im Rheintal vor Mai blühen.",
"Eine zufällig ausgewählte Person in Deutschland liest NICHT monatlich Bücher.",
"Eine zufällig ausgewählte Person in Deutschland liest monatlich Bücher.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Facebook NICHT täglich.",
"Eine zufällig ausgewählte Person in Deutschland nutzt täglich Facebook." ,
"Ein zufällig ausgewähltes Gebäude in Deutschland hat NICHT mehr als 4 Stockwerke.",
"Ein zufällig ausgewähltes Gebäude in Deutschland hat mehr als 4 Stockwerke.",
"Ein zufällig ausgewählte deutsche Hochschulstudent studiert in den Bereichen Technik und Ingenieurwesen.",
"Ein zufällig ausgewählte deutsche Hochschulstudent studiert NICHT in den Bereichen Technik und Ingenieurwesen.",
"An einem zufällig ausgewählten Tag im Dezember wird die Durchschnittstemperatur in Deutschland über 0 °C liegen.",
"An einem zufällig ausgewählten Tag im Dezember wird die Durchschnittstemperatur in Deutschland NICHT über 0 °C liegen.",
"Eine zufällig ausgewählte Person in Deutschland liest NICHT täglich Bücher.",
"Eine zufällig ausgewählte Person in Deutschland liest täglich Bücher.",
"Eine zufällig ausgewählte Person in Deutschland im Alter von 20 bis 25 Jahren studiert an einer Universität oder Hochschule.",
"Eine zufällig ausgewählte Person in Deutschland im Alter von 20 bis 25 Jahren studiert NICHT an einer Universität oder Hochschule." ,
"Ein zufällig ausgewähltes Auto auf der Straße in Deutschland ist von einer deutschen Automarke.",
"Ein zufällig ausgewähltes Auto auf der Straße in Deutschland ist NICHT von einer deutschen Automarke.",
"Eine zufällig ausgewählte deutsche Person ist NICHT Mitglied der christlichen Kirche.", "Eine zufällig ausgewählte deutsche Person ist Mitglied der christlichen Kirche.",
"Eine zufällig ausgewählte Person in Deutschland wird irgendwann an einer Herzerkrankung sterben.",
"Eine zufällig ausgewählte Person in Deutschland wird NICHT irgendwann an einer Herzerkrankung sterben.",
"Ein zufällig ausgewähltes Ehepaar in Deutschland hat Kinder.",
 "Ein zufällig ausgewähltes Ehepaar in Deutschland hat KEINE Kinder.",
 "In einem zufällig ausgewählten Jahr werden die Osterglocken in Deutschland im Februar blühen.",
"In einem zufällig ausgewählten Jahr werden die Osterglocken in Deutschland NICHT im Februar blühen.",
"Eine zufällig ausgewählte Person in Deutschland wohnt in Bayern, Baden-Württemberg oder Nordrhein-Westfalen.",
"Eine zufällig ausgewählte Person in Deutschland wohnt NICHT in Bayern, Baden-Württemberg oder Nordrhein-Westfalen.",
"Eine zufällig ausgewählte Person in Deutschland nutzt soziale Medien NICHT täglich.",
"Eine zufällig ausgewählte Person in Deutschland nutzt täglich soziale Medien.",
"An einem zufällig ausgewählten Tag im Jahr wird die Temperatur in Deutschland über 10°C liegen.",
"An einem zufällig ausgewählten Tag im Jahr wird die Temperatur in Deutschland NICHT über 10°C liegen.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich NICHT mehr als 1000 Schritte.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich mehr als 1000 Schritte.",
"Eine zufällig ausgewählte Person in Deutschland im Alter von 20 bis 25 Jahren studiert.",
"Eine zufällig ausgewählte Person in Deutschland im Alter von 20 bis 25 Jahren studiert NICHT." ,
"An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer in ganz Deutschland bei über 6 Stunden liegen.",
"An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer für ganz Deutschland NICHT bei über 6 Stunden liegen.",
"An einem zufällig ausgewählten Tag im Dezember wird die Durchschnittstemperatur in Deutschland über 5 °C liegen.",
"An einem zufällig ausgewählten Tag im Dezember wird die Durchschnittstemperatur in Deutschland NICHT über 5 °C liegen.",
"Eine zufällig ausgewählte Person in Deutschland nutzt monatlich Facebook.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Facebook NICHT monatlich.",
"Eine zufällig ausgewählte Person in Deutschland, die über 20 Jahre alt ist, besitzt ein Auto.",
"Eine zufällig ausgewählte Person in Deutschland, die über 20 Jahre alt ist, besitzt KEIN Auto.", 
"In einer zufällig ausgewählten deutschen Stadt gibt es NICHT mehr Bäume als Häuser.",
"In einer zufällig ausgewählten deutschen Stadt gibt es mehr Bäume als Häuser.",
"Eine zufällig ausgewählte Person in Deutschland wohnt NICHT in einer Wohnung.",
"Eine zufällig ausgewählte Person in Deutschland wohnt in einer Wohnung.",
"Eine zufällig ausgewählte Person in Deutschland geht NICHT täglich joggen.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich joggen.",
"Eine zufällig ausgewählte Person in Deutschland war noch NICHT in Asien.",
"Eine zufällig ausgewählte Person in Deutschland war schon in Asien.",
"Eine zufällig ausgewählte Person in Deutschland über 20 Jahre ist verheiratet." ,
"Eine zufällig ausgewählte Person in Deutschland über 20 Jahre ist NICHT verheiratet." ,
"Ein zufällig ausgewähltes deutsches Schulkind lernt in der Schule KEINE andere erste Fremdsprache als Englisch.",
 "Ein zufällig ausgewähltes deutsches Schulkind lernt in der Schule eine andere erste Fremdsprache als Englisch.",
"Ein zufällig ausgewählter Zug in Deutschland fährt NICHT pünktlich ab.",
"Ein zufällig ausgewählter Zug in Deutschland fährt pünktlich ab.",
 "Eine zufällig ausgewählte über 18-jährige Person in Deutschland hat einen Bürojob.",
"Eine zufällig ausgewählte über 18-jährige Person in Deutschland hat KEINE Bürojob.",
"In einem zufällig ausgewählten Haushalt in Deutschland gibt es NICHT mehr als zwei Haushaltsmitglieder.", 
"In einem zufällig ausgewählten Haushalt in Deutschland gibt es mehr als zwei Haushaltsmitglieder.",
"An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer in ganz Deutschland über 5 Stunden liegen.",
"An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer in ganz Deutschland NICHT über 5 Stunden liegen.",
"An einem zufällig ausgewählten Tag im Dezember wird die Durchschnittstemperatur in Deutschland über 3 °C liegen.",
"An einem zufällig ausgewählten Tag im Dezember wird die Durchschnittstemperatur in Deutschland NICHT über 3 °C liegen.",
"Eine zufällig ausgewählte Person in Deutschland liest NICHT wöchentlich Bücher.",
"Eine zufällig ausgewählte Person in Deutschland liest wöchentlich Bücher.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich NICHT mehr als 800 Meter.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich mehr als 800 Meter.",
"Eine zufällig ausgewählte Person in Deutschland hat mehr als ein Geschwisterkind.",
"Eine zufällig ausgewählte Person in Deutschland hat NICHT mehr als ein Geschwisterkind.",
"Eine zufällig ausgewählte Person in Deutschland im Alter von 18 bis 25 Jahren studiert.",
"Eine zufällig ausgewählte Person in Deutschland im Alter von 18 bis 25 Jahren studiert NICHT.",
"In einem zufällig ausgewählten Jahr wird die Kirschblüte in Deutschland vor Mitte März beginnen.",
"In einem zufällig ausgewählten Jahr wird die Kirschblüte in Deutschland NICHT vor Mitte März beginnen.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Twitter regelmäßig im Alltag.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Twitter NICHT regelmäßig im Alltag.",
"Eine zufällig ausgewählte Person in Deutschland besitzt KEIN Auto.",
"Eine zufällig ausgewählte Person in Deutschland besitzt ein Auto.", 
"In einem zufällig ausgewählten Jahr werden in Deutschland im April mehr Blumenarten blühen als im März.",
"In einem zufällig ausgewählten Jahr werden in Deutschland im April NICHT mehr Blumenarten blühen als im März.", 
"An einem zufällig ausgewählten Tag im Jahr wird die Temperatur in Deutschland über 12°C liegen.",
"An einem zufällig ausgewählten Tag im Jahr wird die Temperatur in Deutschland NICHT über 12°C liegen.",
"Eine zufällig ausgewählte Person in Deutschland wird irgendwann an einer Herz-Kreislauf-Erkrankung sterben.", 
"Eine zufällig ausgewählte Person in Deutschland wird NICHT irgendwann an einer Herz-Kreislauf-Erkrankung sterben.", "Ein zufällig ausgewählter Pendler fährt NICHT mit dem Fahrrad zur Arbeit.", 
"Ein zufällig ausgewählter Pendler fährt mit dem Fahrrad zur Arbeit.",
"Eine zufällig ausgewählte Person in Deutschland besitzt KEINE Hunde.",
"Eine zufällig ausgewählte Person in Deutschland besitzt einen oder mehrere Hunde.",                                                               
"In einem zufällig ausgewählten Jahr wird es in Deutschland im Juni KEINE größere Vielfalt an Früchten auf dem Markt geben als im Juli.", 
"In einem zufällig ausgewählten Jahr wird es in Deutschland im Juni eine größere Vielfalt an Früchten auf dem Markt geben als im Juli.", 
"Ein zufällig ausgewähltes Ehepaar in Deutschland hat nur ein Kind.", 
"Ein zufällig ausgewähltes Ehepaar in Deutschland hat NICHT nur ein Kind.",
"Eine zufällig ausgewählte Person in Deutschland noch NIE Geld an eine wohltätige Organisation gespendet.", 
"Eine zufällig ausgewählte Person in Deutschland schon einmal Geld an eine wohltätige Organisation gespendet.", 
"Eine zufällig ausgewählte Person in Deutschland kann NICHT Ski fahren.", 
"Eine zufällig ausgewählte Person in Deutschland kann Ski fahren.",
"Eine zufällig ausgewählte Person in Deutschland isst täglich Gemüse.",
"Eine zufällig ausgewählte Person in Deutschland isst NICHT täglich Gemüse.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Facebook NICHT regelmäßig im Alltag.",
"Eine zufällig ausgewählte Person in Deutschland nutzt Facebook regelmäßig im Alltag.",
"Eine zufällig ausgewählte Person in Deutschland liest im Alltag regemäßig Zeitung.",
"Eine zufällig ausgewählte Person in Deutschland liest im Alltag NICHT regemäßig Zeitung.",
"Eine zufällig ausgewählte Person in Deutschland lebt NICHT in einer Großstadt.",
"Eine zufällig ausgewählte Person in Deutschland lebt in einer Großstadt.",
"Ein zufällig ausgewählter Baum in Deutschland ist KEIN Laubbaum.",
"Ein zufällig ausgewählter Baum in Deutschland ist ein Laubbaum.", 
"Ein(e) zufällig ausgewählte(r) Student(in) in Deutschland studiert in den Bereichen Recht, Wirtschaft oder Sozialwissenschaften.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich im Durchschnitt NICHT mehr als 2000 Schritte.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich im Durchschnitt mehr als 2000 Schritte.",
"An einem zufällig ausgewählten Tag in Hamburg wird es Regen geben.",
"An einem zufällig ausgewählten Tag in Hamburg wird es KEINEN Regen geben.",
"Eine zufällig ausgewählte Person in Deutschland isst täglich mehr als vier Gemüsesorten.",
"Eine zufällig ausgewählte Person in Deutschland isst täglich NICHT mehr als vier Gemüsesorten.",
"In einem zufällig ausgewählten Jahr wird die Höchsttemperatur in Deutschland 36°C oder mehr erreichen.",
"In einem zufällig ausgewählten Jahr wird die Höchsttemperatur in Deutschland NICHT 36°C oder mehr erreichen.")       

```

```{r define plausible_events vector}
plausible_event <- c("In einem zufällig ausgewählten Stadtteil in Deutschland gibt es mindestens eine Bäckerei.",
"In einem zufällig ausgewählten Stadtteil in Deutschland gibt es KEINE Bäckerei.",
"Ein zufällig ausgewähltes 12-jähriges deutsches Kind weiß NICHT, wie man ein Smartphone bedient.",
"Ein zufällig ausgewähltes 12-jähriges deutsches Kind weiß, wie man ein Smartphone bedient.",
"Eine zufällig ausgewählte Person in Deutschland besitzt mindestens ein Gerät, das sich mit dem Internet verbinden kann.",
"Eine zufällig ausgewählte Person in Deutschland besitzt KEIN Gerät, das sich mit dem Internet verbinden kann.",
"In einem zufällig ausgewählten Jahr wird die Höchsttemperatur in Deutschland NICHT 32°C oder mehr erreichen.",
"In einem zufällig ausgewählten Jahr wird die Höchsttemperatur in Deutschland 32°C oder mehr erreichen.",
"Ein zufällig ausgewähltes deutsches Geschäft existiert NICHT seit mehr als 5 Jahren.",
"Ein zufällig ausgewähltes deutsches Geschäft existiert seit mehr als 5 Jahren.",
"In einem zufällig ausgewählten Jahr im Winter wird es in Deutschland Schneestürme geben.",
"In einem zufällig ausgewählten Jahr im Winter wird es in Deutschland KEINE Schneestürme geben.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich im Durchschnitt NICHT mehr als 50 Schritte.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich im Durchschnitt mehr als 50 Schritte.",
"An einem zufällig ausgewählten Tag im August wird das Wetter in Berlin trocken sein.",
"An einem zufällig ausgewählten Tag im August wird das Wetter in Berlin NICHT trocken sein.",
"Eine zufällig ausgewählte Person in Deutschland wird sich im Laufe ihres Lebens eine Grippe einfangen.",
"Eine zufällig ausgewählte Person in Deutschland wird sich im Laufe ihres Lebens KEINE Grippe einfangen.",
"An einem zufällig ausgewählten Tag wird die Luftqualität NICHT akzeptabel für die Mehrheit der Bevölkerung in Deutschland sein.",
"An einem zufällig ausgewählten Tag wird die Luftqualität akzeptabel für die Mehrheit der Bevölkerung in Deutschland sein.",
"In einem zufällig ausgewählten Haushalt in Deutschland gibt es KEINE IKEA-Produkte.",
"In einem zufällig ausgewählten Haushalt in Deutschland gibt es IKEA-Produkte.",
"Eine zufällig ausgewählte Person in Deutschland wurde NICHT in einem Krankenhaus geboren.",
"Eine zufällig ausgewählte Person in Deutschland wurde in einem Krankenhaus geboren.",
"Ein zufällig ausgewähltes deutsches Geschäft wird samstags NICHT geöffnet sein.",
"Ein zufällig ausgewähltes deutsches Geschäft wird samstags geöffnet sein.",
"Eine zufällig ausgewählte Person, die vor 8 Uhr morgens durch eine deutsche Stadt läuft, ist auf dem Weg zur Arbeit.",
"Eine zufällig ausgewählte Person, die vor 8 Uhr morgens durch eine deutsche Stadt läuft, ist NICHT auf dem Weg zur Arbeit.",
"Eine zufällig ausgewählte Person in Deutschland geht durchschnittlich NICHT mehr als 100 Meter täglich.",
"Eine zufällig ausgewählte Person in Deutschland geht durchschnittlich mehr als 100 Meter täglich.",
"Ein(e) zufällig ausgewählte(r) Student(in) spricht KEIN Englisch.",
"Ein(e) zufällig ausgewählte(r) Student(in) spricht Englisch.",
"In einer zufällig ausgewählten deutschen Stadt gibt es im Winter einen Weihnachtsmarkt.",
"In einer zufällig ausgewählten deutschen Stadt gibt es im Winter KEINEN Weihnachtsmarkt.",
"In einem zufällig ausgewählten deutschen Haushalt werden wir KEINE Pflanzen finden.",
"In einem zufällig ausgewählten deutschen Haushalt werden wir Pflanzen finden.", 
"Eine zufällig ausgewählte Person in Deutschland ist auf die Realschule gegangen.",
"Eine zufällig ausgewählte Person in Deutschland ist NICHT auf die Realschule gegangen.",
"In einem zufällig ausgewählten Jahr wird der August der heißeste Monat in Deutschland sein.",
"In einem zufällig ausgewählten Jahr wird der August NICHT der heißeste Monat in Deutschland sein.",
"In einer zufällig ausgewählten deutschen Stadt gibt es KEINE Soccer-Klub.",
 "In einer zufällig ausgewählten deutschen Stadt gibt es mindestens einen Soccer-Klub.",
"Ein zufällig ausgewählter achtjähriger deutscher Junge spielt gerne Fußball.",
"Ein zufällig ausgewählter achtjähriger deutscher Junge spielt NICHT gerne Fußball.",
"Ein zufällig ausgewählter deutscher Erwachsener kann Fahrrad fahren.",
"Ein zufällig ausgewählter deutscher Erwachsener kann KEIN Fahrrad fahren.",
"Ein zufällig ausgewähltes deutsches Geschäft existiert NICHT seit mehr als 3 Jahren.",
"Ein zufällig ausgewähltes deutsches Geschäft existiert seit mehr als 3 Jahren.",
"Eine zufällig ausgewählte Person in Deutschland hat mindestens ein WM-Fußballspiel in seinem/ihrem Leben gesehen.",
"Eine zufällig ausgewählte Person in Deutschland hat KEIN WM-Fußballspiel in seinem/ihrem Leben gesehen.",
"In einem zufällig ausgewählten Jahr wird die niedrigste Temperatur in Deutschland NICHT unter -10°C liegen.",
"In einem zufällig ausgewählten Jahr wird die niedrigste Temperatur in Deutschland unter -10°C liegen.",
"Ein zufällig ausgewählter deutscher Supermarkt wird an einem typischen Samstag NICHT mit Menschen überfüllt sein.",
"Ein zufällig ausgewählter deutscher Supermarkt wird an einem typischen Samstag mit Menschen überfüllt sein.",
"In einem zufällig ausgewählten Jahr wird es in Deutschland Hagelstürme geben.",
"In einem zufällig ausgewählten Jahr wird es in Deutschland KEINE Hagelstürme geben.",
"Eine zufällig ausgewählte Person in Deutschland wird im Laufe ihres Lebens eine Erkältung bekommen.",
"Eine zufällig ausgewählte Person in Deutschland wird im Laufe ihres Lebens KEINE Erkältung bekommen.",
"In einem zufällig ausgewählten Jahr wird den ganzen März über Schnee auf dem Gipfel der Zugspitze in Deutschland sein.",
"In einem zufällig ausgewählten Jahr wird den ganzen März über KEIN Schnee auf dem Gipfel der Zugspitze in Deutschland sein.",
"In einem zufällig ausgewählten deutschen Haushalt findet man KEINE Waschmaschine.",
"In einem zufällig ausgewählten deutschen Haushalt findet man mindestens eine Waschmaschine.",
"In einem zufällig ausgewählten Sommer wird es KEINE Überschwemmungen in Deutschland geben.",
"In einem zufällig ausgewählten Sommer wird es Überschwemmungen in Deutschland geben.",
"Eine zufällig ausgewählte Person in Deutschland ist NICHT auf das Gymnasium gegangen.",
"Eine zufällig ausgewählte Person in Deutschland ist auf das Gymnasium gegangen.",
"Eine zufällig ausgewählte Person in Deutschland war schon einmal in Frankreich.",
"Eine zufällig ausgewählte Person in Deutschland war noch NIE in Frankreich.",
"Ein zufällig ausgewählter deutscher Haushalt besitzt ein Auto." ,
"Ein zufällig ausgewählter deutscher Haushalt besitzt KEIN Auto.",
"In einem zufällig ausgewählten Jahr wird die Höchsttemperatur in Deutschland NICHT 30°C oder mehr erreichen.",
"In einem zufällig ausgewählten Jahr wird die Höchsttemperatur in Deutschland 30°C oder mehr erreichen.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich mehr als 100 Schritte.",
"Eine zufällig ausgewählte Person in Deutschland geht täglich NICHT mehr als 100 Schritte.",
"In einem zufällig ausgewählten Jahr werden der Juli und der August NICHT die heißesten Monate in Deutschland sein.", 
"In einem zufällig ausgewählten Jahr werden der Juli und der August die heißesten Monate in Deutschland sein.",
"An einem zufällig ausgewählten Tag im Winter wird Schnee auf dem Gipfel der Zugspitze liegen.",
"An einem zufällig ausgewählten Tag im Winter wird KEIN Schnee auf dem Gipfel der Zugspitze liegen.",
"Ein zufällig ausgewähltes 10-jähriges deutsches Kind weiß NICHT, wie man ein Smartphone bedient.",
"Ein zufällig ausgewähltes 10-jähriges deutsches Kind weiß, wie man ein Smartphone bedient.",
"In einem zufällig ausgewählten Jahr wird die niedrigste Temperatur in Deutschland unter -5°C liegen.",
"In einem zufällig ausgewählten Jahr wird die niedrigste Temperatur in Deutschland NICHT unter -5°C liegen.",
"Ein zufällig ausgewähltes Gebäude in Deutschland hat NICHT mehr als 3 Stockwerke." ,
"Ein zufällig ausgewähltes Gebäude in Deutschland hat mehr als 3 Stockwerke.",
"In einem zufällig ausgewählten Haushalt in Deutschland gibt es ein Bücherregal.",
"In einem zufällig ausgewählten Haushalt in Deutschland gibt es KEIN Bücherregal.",
"Ein zufällig ausgewählter Grundschuljunge spielt NICHT gerne Fußball.",
"Ein zufällig ausgewählter Grundschuljunge spielt gerne Fußball.",
"Ein(e) zufällig ausgewählte(r) Student(in) in Deutschland studiert in den Bereichen Recht, Wirtschaft oder Sozialwissenschaften.",
"Ein zufällig ausgewähltes deutsches Geschäft wird dienstags geöffnet sein.",
"Ein zufällig ausgewähltes deutsches Geschäft wird dienstags NICHT geöffnet sein.",
"An einem zufällig ausgewählten Tag in Deutschland wird es Luftverschmutzung geben.",
"An einem zufällig ausgewählten Tag in Deutschland wird es KEINE Luftverschmutzung geben.",
"In einem zufällig ausgewählten Jahr wird der August der heißeste Monat in Deutschland sein.",
"In einem zufällig ausgewählten Jahr wird der August NICHT der heißeste Monat in Deutschland sein.",
"Ein zufällig ausgewähltes Haus in Deutschland hat mehr als 2 Stockwerke.",                                               
"Ein zufällig ausgewähltes Haus in Deutschland hat NICHT mehr als 2 Stockwerke.")    

# "An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer in ganz Deutschland bei über 7 Stunden liegen.",
# "An einem zufällig ausgewählten Tag im Jahr wird die Sonnenscheindauer für ganz Deutschland NICHT bei über 7 Stunden liegen.",

```

```{r three sub-datesets}
df <- df %>% mutate(event_type = ifelse(event_item %in% diff_event, "indiff",
                                        ifelse(event_item %in% plausible_event, "plau", "implau")))


df_indiff <- df %>% filter(event_type == "indiff")
df_plau <- df %>% filter(event_type == "plau")
df_implau <- df %>% filter(event_type == "implau")


df_indiff <- df_indiff %>% 
    mutate(item_id = group_indices_(df_indiff, .dots=c("labelling"))) %>%
  select(ID, event_type, event_item, answer, event_comp, item_id)

df_plau <- df_plau %>% 
  mutate(item_id = group_indices_(df_plau, .dots=c("labelling"))) %>%
  select(ID, event_type, event_item, answer, event_comp, item_id)



df_implau <- df_implau %>% 
  mutate(item_id = group_indices_(df_implau, .dots=c("labelling"))) %>%
  select(ID, event_type, event_item, answer, event_comp, item_id)

```


```{r draw indiff plots}

df_indiff <- df_indiff %>% mutate(group_number = ifelse(item_id %in% c(1:25), "1", 
                                          ifelse(item_id %in% c(26:50),"2",
                                                 ifelse(item_id %in% c(51:75), "3",
                                                        ifelse(item_id %in% c(74:100), "4", "NA")))))

df_indiff$item_id <- as.factor(df_indiff$item_id)

 p1 <- ggplot(
  df_indiff, 
  aes(x=answer, y=item_id, fill= event_comp)) +
  geom_density_ridges(quantile_lines = T, quantile_fun = mean,
                      vline_color = "blue",
                      panel_scaling = FALSE,
                      scale = 3, size = 0.3, rel_min_height = 0.01, alpha = 0.7) +
  scale_x_continuous(breaks = seq(0, 100, 10)) + 
  theme(axis.text.x = element_text(size = 4),
        axis.text.y = element_text(size = 4)) + 
  geom_vline(xintercept=c(0, 20, 50, 80, 100), linetype="dotted") +
  facet_wrap(.~group_number, scales = "free") + 
   theme(strip.text.x = element_blank())
 
p1
ggsave("p1_indiff.png")

 p2 <- ggplot(
 df_indiff, 
  aes(x=answer, y=item_id, fill= event_comp)) +
  geom_density_ridges(quantile_lines = T, quantile_fun = mean,
                      vline_color = "blue", vline_type = "dotted",
                      panel_scaling = FALSE,
                      scale = 3, size = 0.3, rel_min_height = 0.01, alpha = 0.7) +
  scale_x_continuous(breaks = seq(0, 100, 10)) + 
  theme(axis.text.x = element_text(size = 4),
        axis.text.y = element_text(size = 4)) + 
  geom_vline(xintercept=c(0, 20, 50, 80, 100), linetype="dotted") +
  # facet_wrap(.~group_number, scales = "free_y", ncol = 1) + 
   theme(strip.text.x = element_blank()) + 
   theme(plot.margin = margin(0.1, 4, 0.1, 4, "cm"))
 
 p2

```


```{r draw plausible_events plots}

df_plau <- df_plau %>% mutate(group_number = ifelse(item_id %in% c(1:25), "1", 
                                          ifelse(item_id %in% c(26:50),"2", "NA")))

df_plau$item_id <- as.factor(df_plau$item_id)

 p3 <- ggplot(
  df_plau, 
  aes(x=answer, y=item_id, fill= event_comp)) +
  geom_density_ridges(quantile_lines = T, quantile_fun = mean,
                      vline_color = "blue",
                      panel_scaling = FALSE,
                      scale = 3, size = 0.3, rel_min_height = 0.01, alpha = 0.7) +
  scale_x_continuous(breaks = seq(0, 100, 10)) + 
  theme(axis.text.x = element_text(size = 4),
        axis.text.y = element_text(size = 4)) + 
  geom_vline(xintercept=c(0, 20, 50, 80, 100), linetype="dotted") +
  facet_wrap(.~group_number, scales = "free") + 
   theme(strip.text.x = element_blank())
 
 p3
ggsave("p3_plau.png")

# no.18 excluded: In einem zufällig ausgewählten Sommer wird es Überschwemmungen in Deutschland geben.
# no.11 excluded: In einem zufällig ausgewählten Jahr wird die niedrigste Temperatur in Deutschland unter -10°C liegen.
# no.6 excluded:  Eine zufällig ausgewählte Person in Deutschland ist auf die Realschule gegangen.
# no.34 excluded:  An einem zufällig ausgewählten Tag im August wird das Wetter in Berlin trocken sein.
# no.33 excluded: In einem zufällig ausgewählten Jahr im Winter wird es in Deutschland Schneestürme geben.
# no.29 excluded: Ein zufällig ausgewähltes Gebäude in Deutschland hat mehr als 3 Stockwerke.
# no.27 excluded: Eine zufällig ausgewählte Person in Deutschland ist auf das Gymnasium gegangen.
# no.26 excluded:  Ein zufällig ausgewählter deutscher Haushalt besitzt ein Auto.
 
```


```{r draw implausible_events plots}

df_implau <- df_implau %>% mutate(group_number = ifelse(item_id %in% c(1:25), "1", 
                                          ifelse(item_id %in% c(26: 53),"2", "NA")))

df_implau$item_id <- as.factor(df_implau$item_id)

 p4 <- ggplot(
  df_implau, 
  aes(x=answer, y=item_id, fill= event_comp)) +
  geom_density_ridges(quantile_lines = T, quantile_fun = mean,
                      vline_color = "blue",
                      panel_scaling = FALSE,
                      scale = 3, size = 0.3, rel_min_height = 0.01, alpha = 0.7) +
  scale_x_continuous(breaks = seq(0, 100, 10)) + 
  theme(axis.text.x = element_text(size = 4),
        axis.text.y = element_text(size = 4)) + 
  geom_vline(xintercept=c(0, 20, 50, 80, 100), linetype="dotted") +
  facet_wrap(.~group_number, scales = "free") + 
   theme(strip.text.x = element_blank())
 
 p4
 ggsave("p4_implau.png")
 
```


```{r}

# create tables to look up items 
df_implau_v <- df_implau %>%
  group_by(event_item) %>% 
  mutate(mean_event_item = mean(answer),
         sd_event_item = sd(answer)) %>% 
  select(item_id, event_item, mean_event_item, sd_event_item) %>% unique()


df_plau_v <- df_plau %>%
  group_by(event_item) %>% 
  mutate(mean_event_item = mean(answer),
         sd_event_item = sd(answer)) %>% 
  select(item_id, event_item, mean_event_item, sd_event_item) %>% unique()


df_indiff_v <- df_indiff %>%
  group_by(event_item) %>% 
  mutate(mean_event_item = mean(answer),
         mean_distance = abs(50 - mean(answer)),
         sd_event_item = sd(answer)) %>% 
  select(item_id, event_item, mean_event_item, mean_distance, sd_event_item) %>% unique()

write.csv(df_implau_v,"df_implau_v.csv", row.names = FALSE)
write.csv(df_plau_v,"df_plau_v.csv", row.names = FALSE)
write.csv(df_indiff_v,"df_indiff_v.csv", row.names = FALSE)
```



